### ISSUE TITLE
[Bug] Notification flooding, failure to disable, and freezing.

### ISSUE THREAD

**Issue by 48-mq** [Alfio010/notification-listener-android#13]
Several minutes after installing the app and enabling all the sought permissions, I started receiving a flood of notifications from this app about supposedly previous deleted notifications. Only these were all indicating a persistent notification from another app that uses a foreground service.

When I tried to turn off the notifications in the settings menu, the switch would turn off but the notifications continued flooding in. I tried force-stopping the app but the notifications flood would promptly resume upon startup.

So I finally I just revoked the notifications permission to restore the peace. But now when I start the app, it just freezes. I cannot click on any of the buttons, neither can I go into the "hamburger" menu.

**Comment by Alfio010** [comment]
Fixed with version 2.2
