### ISSUE TITLE
[Security] Biometrics authentication is relying on an abandoned alpha library

### ISSUE THREAD

**Issue by MarkDevelops1995** [Alfio010/notification-listener-android#18]
I love this application.

But:
* The biometrics authentication system is utilizing a not up-to-date library, which is also an alpha version. This concerns me, and probably other users, due to the fact that the authentication process is a very security-critical part of the app.

The main problem is in the `androidx.biometric:biometric-ktx` library:
I've noticed that a version `1.4.0-alpha02` is present. While your application **STILL** uses version `1.2.0-alpha05`.

Possible solutions:
* Utilize a different, updated, library. Hopefully non-alpha nor beta releases.
* Write your own custom biometrics handling code.

**Comment by Alfio010** [comment]
Hi, I've been busy lately, but as a fix I will update the library to the latest version

**Comment by Alfio010** [comment]
Hi, I've been busy lately, but as a fix I will update the library to the latest version

**Comment by Alfio010** [comment]
done
