### ISSUE TITLE
 [UNEXPECTED BEHAVIOUR] Application Fails to Retain Notification Settings

### ISSUE THREAD

**Issue by MarkDevelops1995** [Alfio010/notification-listener-android#19]
I am experiencing a **BUG** where the application **DOES NOT** remember my preference to **disable** notifications. Despite turning off notifications, the setting reverts to enabled after closing and reopening the app.

## Steps to Reproduce

- Open the app.
- Navigate to the notification settings and disable notifications.
- Close the app completely.
- Reopen the app.

## Expected Behavior
- The app should retain the notification settings and keep notifications disabled until I choose to enable them again.

## Actual Behavior
- Upon reopening the app, the notification setting defaults back to enabled.

## Environment
- App Version: 2.2.2
- Telephone: UMIDIGI G1 Tab Mini Kids
- OS Version: Android 14

**Comment by Alfio010** [comment]
fixed
